/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.ImmutableSet;

public class HelloOtus {
  public static void main(String... args) {
    System.out.println(ImmutableSet.of("Red", "Green", "Blue", "Yellow", "Green").toString());
  }
}
