/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import ru.otus.executor.CustomTestExecutor;

import java.util.List;

public class LessonThreeMain {

  public static void main(String... args) {
      new CustomTestExecutor().execute(List.of("ru.otus.tests.TestedClassOneTest", "ru.otus.tests.TestedClassTwoTest"));
  }
}
